name: Waka Readme
on:
  schedule:
    - cron: '0 0 * * *' # 每日UTC0点运行
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
  - uses: anmol098/waka-readme-stats@master
    with:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      LOCALE: zh
      # 主要显示模块
      SHOW_TOTAL_CODE_TIME: "True"   # 总编码时间徽章
      SHOW_PROFILE_VIEWS: "True"     # 资料查看次数徽章
      SHOW_COMMIT: "True"            # GitHub提交数据板块
      SHOW_TIME_OF_DAY: "True"       # 日活跃时段图表
      SHOW_DAYS_OF_WEEK: "True"      # 周活跃日期图表
      # 本周详细统计
      SHOW_LANGUAGE: "True"          # 编程语言
      SHOW_EDITORS: "True"           # 编辑器
      SHOW_PROJECTS: "True"          # 项目
      SHOW_OS: "True"                # 操作系统
      # 其他可选参数（可根据喜好调整）
      # SHOW_TITLE: "False"          # 是否显示“WakaTime周统计”标题
      # TIME_RANGE: "last_7_days"    # 统计时间范围，可选 "last_30_days"
